version: "3.1"

services:
  postgres:
    image: postgres:14
    environment:
     POSTGRES_PASSWORD: ikigai
     POSTGRES_USER: ikigai
     POSTGRES_DB: ikigai
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    ports:
      - "6379:6379"
  migration:
    platform: "linux/amd64"
    build:
      dockerfile: Migration.Dockerfile
    environment:
      DATABASE_URL: postgres://ikigai:ikigai@postgres:5432/ikigai
    depends_on:
      postgres:
        condition: service_healthy
  graphql-server:
    platform: "linux/amd64"
    build:
      dockerfile: Dockerfile
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migration:
        condition: service_completed_successfully
    network_mode: host
