version: '3.1'

services:
  postgres:
    image: postgres:14
    environment:
     POSTGRES_PASSWORD: openexam
     POSTGRES_USER: openexam
     POSTGRES_DB: openexam
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
  redis:
    image: redis
    ports:
      - "6379:6379"
  migration:
    platform: "linux/amd64"
    build:
      dockerfile: Migration.Dockerfile
    environment:
      DATABASE_URL: postgres://openexam:openexam@postgres:5432/openexam
    depends_on:
      postgres:
        condition: service_healthy
  graphql-server:
    platform: "linux/amd64"
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://openexam:openexam@postgres:5432/openexam
      REDIS_URL: redis://redis:6379
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migration:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
