services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ikigai
      POSTGRES_USER: ikigai
      POSTGRES_DB: ikigai
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  migration:
    image: ghcr.io/ikigai-hq/ikigai-migration:latest
    build:
      dockerfile: Migration.Dockerfile
    environment:
      DATABASE_URL: postgres://ikigai:ikigai@postgres:5432/ikigai
    depends_on:
      postgres:
        condition: service_healthy
  graphql-server:
    image: ghcr.io/ikigai-hq/ikigai:latest
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migration:
        condition: service_completed_successfully
    network_mode: host
  ikigai-web-client:
    image: ghcr.io/ikigai-hq/ikigai-web:latest
    depends_on: [graphql-server]
    network_mode: host
  ikigai-ai:
    image: ghcr.io/ikigai-hq/ikigai-ai:latest
    depends_on: []
    environment:
      OPENAI_API_KEY: YOUR_OPENAI_API_KEY
    network_mode: host

volumes:
  postgres_data: {}
  redis_data: {}
