name: Check Graphql Server

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./graphql_server

jobs:
  check_clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Clippy Container
        run: |
          docker build -f Workflow.Dockerfile -t ikigai-graphql-server:check .
          docker run ikigai-graphql-server:check
